#

## To compile the java program and copy the .class in the right binary repository*
# javac className.java
# don't forget to copy the .class in the right binary use case dir
# cp LibApexArinc653Jni.class ../../../../binary/UseCases/JNI_Template/LibApexArinc653Jni.class

#  To create the .h to create the jni lib
# javah -jni className

# To get the functions signatures for creating the jni lib
# javap = class file disassembler
# -s = print signature
# -p = show private members
# javap -s -p className
